### ISSUE TITLE
Switch the location of information in Verkefni (sjá mynd)

### ISSUE THREAD

**Issue by jonthorgal** [piratar/grasrotarinn#5]
Hafa 'Verk' áfram fyrir ofan 'Hópur' en láta réttar upplýsingar rata á réttan stað með því að svissa þeim (sjá mynd).
<img width="981" alt="screenshot 2018-01-11 13 15 21" src="https://user-images.githubusercontent.com/35225459/34827543-7a18e5d4-f6d2-11e7-910d-86fe5eecca69.png">

**Comment by HermannBjorgvin** [comment]
Classic bug, easy fix. Right? @jonhilmarg

**Comment by jonhilmarg** [comment]
yebb :)

**Comment by jonthorgal** [comment]
Afgreitt!
